### ISSUE TITLE
[BUG] Multiple instances of problems loading references

### ISSUE THREAD

**Issue by delulugirl** [SnaveSutit/origins-mod-json-schemas#12]
**Describe the bug**
When editing an origin file (located inside `<namespace>/origins`) an error pops up saying there were problems loading references.
This happens when editing powers too,
...And Origins layers.

**To Reproduce**

1. Make any of the files stated above
2. Try editing them
3. Error appears

**Expected behavior**
~~Errors / warnings not appearing, general use still works, it's just a bit irritating to see it just to realize you didn't make a mistake or a typo.
I'm not sure if this is a clientside issue, I have restarted Visual Studio Code.~~

_(EDIT: Yeah no, it broke **multiple** power types... This is really bad.)_

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/161107541/7bf29f3c-f0c9-45d6-80ea-98be460b3cfa)
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/161107541/27f06d55-21ab-4518-bd58-285f35383dbb)
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/161107541/b9567394-d10a-455d-8504-0486e371170c)

**Comment by SnaveSutit** [comment]
It looks like it failed to fetch the JSON Schemas while loading.

Did you try restarting VSCode? That _should_ fix that issue when it pops up, if you're connected to the internet.

**Comment by delulugirl** [comment]
For some reason the issue took a bit of time to resolve on my end. It's fixed now though!
