### ISSUE TITLE
power types condition field

### ISSUE THREAD

**Issue by unrusoanonimo** [SnaveSutit/origins-mod-json-schemas#2]
almost every power type has a condition field, but it doesn't appear on the schemas
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/75674162/54c41eb8-84ac-453f-b365-2046840202ad)
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/75674162/f7c4b12e-1934-4329-a91c-b4ecb713c69b)

**Comment by SnaveSutit** [comment]
This should be fixed now.
