### ISSUE TITLE
[FR] Add schemas for Origins' "Miscellaneous" types (eg. advancements)

### ISSUE THREAD

**Issue by Technicman69** [SnaveSutit/origins-mod-json-schemas#21]
I didn't see it suggested before, but it would be cool to have that in this beauty of a vs plugin.

From what I saw and read, this plugin currently does not support schemas for the types listed on [Origins Docs](https://origins.readthedocs.io/en/latest/misc/advancement_triggers/#) in the "MISCELLANEOUS" tab on the left.
So that would be:
- Advancement triggers
- Item Modifiers (also in loot tables' functions)
- Items (so just origins:orb_of_origin)
- Predicates (also in loot tables' conditions)

I don't think adding support for commands would be nessesary, as there is no support for other commands in "execute_command" action type anyway

![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/110126449/1c650fb4-9363-4cc3-8d1d-ba6fb72a5552)

If you wanted to add it, I also hope that It could be compatible with the Data-pack Helper Plus plugin I'm using for writing datapack, for example advancements, because it currenlt marks it as an error and I wouldn't want its schemas overwritten

![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/110126449/673028cc-aead-4171-908b-297468903ef7)

![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/110126449/7f5120ca-cbc6-41b5-97c1-152b0eec93b1)

I didn't see any alternatives that would have that kind of schemas, so I hope you would be interested in my request

**Comment by SnaveSutit** [comment]
Vanilla files are out of scope for this plugin.

DPH 4.0 is in development and adds updated and improved schemas for these files. You can follow it's development here: https://discord.gg/EbdseuS.
They're pretty close to releasing v4.0.
