### ISSUE TITLE
[BUG] No schema options for `origins:shader` for `"shader": ""`

### ISSUE THREAD

**Issue by Lunatrixen** [SnaveSutit/origins-mod-json-schemas#23]
**Describe the bug**
No schemas appear when trying to autofill for `"shader": ""`

**To Reproduce**
1. Create shader power
2. Create `"shader": ""`
3. See error

**Expected behavior**
A list of shader schemas are suppose to appear

**Screenshots**
![image](https://github.com/user-attachments/assets/1b556bec-d58c-4e9b-a923-d1773e6f30ad)

**Comment by SnaveSutit** [comment]
Fixed.
Will auto-complete post shaders. Still allows generic identifiers too if someone adds a custom shader.
![image](https://github.com/user-attachments/assets/5a608049-0941-4f7f-a6bc-2c660183665a)
