### ISSUE TITLE
[BUG] Origins Extra Keybinds dont register

### ISSUE THREAD

**Issue by Lunatrixen** [SnaveSutit/origins-mod-json-schemas#6]
**Describe the bug**
The extension does not recognize Origins Extra Keybinds, stating "this value is not accepted"

**To Reproduce**

1. Create a active self power
2. set the keybind to an Origins Extra Keybinds
3. see error

**Expected behavior**
Should be an accepted value

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/91378087/a02d7cc2-b516-4b63-91c5-9031fe8d3b9b)

**Comment by Lunatrixen** [comment]
i should put this here to 
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/91378087/b2a47215-b632-440f-a560-fd9e758a5f26)

**Comment by SnaveSutit** [comment]
Oh, Interesting. It should just accept any old string.
I'll make a patch later tonight.

**Comment by SnaveSutit** [comment]
Fixed in latest
