### ISSUE TITLE
[BUG] Incorrect Linking

### ISSUE THREAD

**Issue by Lunatrixen** [SnaveSutit/origins-mod-json-schemas#8]
**Describe the bug**
Origins Extra Keybinds desc links to extra origins and not Origins Extra Keybinds
**To Reproduce**
1. Create a power
2. Make an active self
3. Make the keybind a Origins Extra Keybind
4. Hover over keybind
5. See bug

**Expected behavior**
Should say "Requires Origins Extra Keybinds to be installed!" and linked to Origins Extra Keybinds

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/91378087/f8554cb1-2839-4d75-90ea-8f03141b5d7b)

**Comment by SnaveSutit** [comment]
Fixed in latest
